### ISSUE TITLE
Enhancer builder gets added twice

### ISSUE THREAD

**Issue by turbomanage** [gwt-eclipse-plugin/gwt-eclipse-plugin#45]
Scenario: I'm trying to import a maven App Engine project using GPE on Ubuntu.

DataNucleus Enhancer is turned on by default, even though I'm using Objectify instead of JPA. I have to manually uncheck the Enhancer builder in project properties.

When I added appengine-java-sdk dependency to the pom as required by GPE, it added ANOTHER Enhancer builder, which I also had to disable

**Comment by branflake2267** [comment]
I'm going to close. I can't reproduce this condition. Feel free to re-open it if you still see the bug. Thanks.
