### ISSUE TITLE
Support older version of GWT SDK without SDM support

### ISSUE THREAD

**Issue by metteo** [gwt-eclipse-plugin/gwt-eclipse-plugin#61]
The new plugin doesn't work well with some old versions of GWT (like 2.0.4...) because they don't know "-noSuperDevMode" parameter. 

Would it be problematic to add some check for GWT SDK version - let's say for GWT < 2.5.0 "-noSuperDevMode" would not be added in launch configuration arguments? Without this check every time developer wants to start classic DevMode he has to manually remove that argument from the list...

I understand that older versions are not maintained anymore but in some projects upgrade would be very expensive and this small change in the plugin would help a lot.

**Comment by branflake2267** [comment]
Thanks for reporting. I've marked it as a bug and will look at adding the sdm arg processor. I hadn't considered older than 2.4.0.

**Comment by metteo** [comment]
According to this: https://github.com/gwt-eclipse-plugin/gwt-eclipse-plugin/blob/master/plugins/com.google.gwt.eclipse.core/src/com/google/gwt/eclipse/core/launch/processors/SuperDevModeArgumentProcessor.java#L138 support for GWT versions older than 2.5.0 is already there and SDM specific arguments are removed in such case. I guess I took GPE as this plugin by mistake... @branflake2267 could you confirm?

**Comment by branflake2267** [comment]
In GPE this is a bug. I had a patch for it, but do to bandwidth, it wasn't able to be merged. In this case have you tried this plugin to see if it still exists? It should be fixed.

**Comment by metteo** [comment]
I installed Luna and this plugin and -nosuperDevMode is not added. I even tried adding both -superDevMode and nosuperDevMode but after saving launch config and reopening it SDM args are removed. Tested with GWT 2.0.3

**Comment by branflake2267** [comment]
The args will get removed once the sdm arg processor is activated again. Sounds like its working then. I'll close the issue. Reply to continue.

**Comment by skarzhevskyy** [comment]
current  GWT 2.8.0-SNAPSHOT and latest plugin on Mars :
Tried to use -nosuperDevMode  in  .launch and it is removed automatically by plugin.   

I understand that 2.8 is not yet final and it is unknown if it will be supporter or not. 
Any suggestion or workaround for this ?

Can you please specify the reason for removing the arguments that where manual added?
If there would be an option to tell plugin --do-not-auto-ccorrect  would be nice.

**Comment by branflake2267** [comment]
Hm, that should work I think. There must be a broken path. How is the project structured.

**Comment by skarzhevskyy** [comment]
Nothing special 
Server separate, GWT app separate.

complete sample app here:
https://github.com/skarzhevskyy/gwt-zerro-app

![05-08-2015 23-30-07](https://cloud.githubusercontent.com/assets/6963441/9103255/0b500e5e-3bca-11e5-93da-6b6f0de1fb3d.png)

**Comment by branflake2267** [comment]
Gotcha, having a separate server should work fine. Although I haven't been testing using the launch files there. Tell you the truth I don't even use those any more, it's been so long I can't remember what those are useful for. 

Running debug as will automatically create a launch configuration. 
![screen shot 2015-08-05 at 10 06 56 pm](https://cloud.githubusercontent.com/assets/1326504/9104225/4f5a2f64-3bbe-11e5-9774-c3adef93a2f4.png)

**Comment by skarzhevskyy** [comment]
I tried this on my configuration.
First it get me to Error: Could not find or load main class
com.google.gwt.dev.GWTShell
and once corrected to com.google.gwt.dev.DevMode and setup by adding -war
"${workspace_loc:test-server-jetty}/src/main/webapp"  still reverts
to Super Dev Mode ...

I have complex app  and multiple developers so setting the urls and
directories on each computer each branch is simply not an option. so we
keep reconfigured setting in git. for each gwt application.


BWT all works fine in when changing to GWT 2.7...

Vlad
